# Generated by Django 4.0.1 on 2022-04-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shogun_speaks', '0002_remove_post_image_name_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
