# Generated by Django 4.0.1 on 2022-04-07 18:01

import django.core.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Shogun_speaks', '0003_remove_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
